openeuropa/oe_content

modules/oe_content_announcement/config/install/rdf_entity.mapping.rdf_entity.oe_announcement.yml, modules/oe_content_event/config/install/rdf_entity.mapping.rdf_entity.oe_event.yml
Added RDF mapping for 
* langcode (string)
* default_langcode (bool)
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1145: Map the translation fields of all content types

README.md, behat.yml.dist, oe_content.install, oe_content.module, runner.yml.dist, tests/Behat/RdfEntityContext.php, tests/features/announcement.feature, tests/features/event.feature, tests/features/provenance_uri.feature
* Access check on edit/delete
* Test
* Temporary extension of the ConfigContext until a PR gets merged in drupal extension project
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1111: Entities originating from external producers should be read only

oe_content.module, oe_content.services.yml, src/EventSubscriber/RdfAdminRouteSubscriber.php
Using the admin theme on RDF entity management routes.
No Kernel tests cause we cant run them in D8.6
Added also missing strict typing in the oe_content module.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
vendor/bin/drush en field_ui
```
=> OPENEUROPA-1178: RDF bundles should use the admin theme for editing purpose

composer.json
In oe_content we use rdf_entity fork on openeuropa organisation, in doing so we specify an alternative repository from where to fetch that fork in the project's composer.json: it turns out that such a repository is not considered when using the component on a site
The scope of this PR is to switch to use patches which are, instead, applied when installing the component.
=> OPENEUROPA-1161: Apply patches to rdf_entity instead of using GitHub fork

composer.json, modules/oe_content_announcement/config/install/core.entity_view_display.rdf_entity.oe_announcement.default.yml, modules/oe_content_announcement/oe_content_announcement.info.yml, modules/oe_content_event/config/install/core.entity_view_display.rdf_entity.oe_event.default.yml, oe_content.services.yml, src/EventSubscriber/RdfEntityRedirectSubscriber.php, src/Plugin/Field/FieldFormatter/RdfEntityReferenceAbsoluteUrlFormatter.php, src/Plugin/Field/FieldFormatter/RdfEntityReferenceDepartmentUrlFormatter.php, src/Plugin/Field/FieldFormatter/RdfEntityReferenceLabelFormatterBase.php, tests/Behat/RdfEntityContext.php, tests/features/department.feature
* Created the 2 formatters
* Wrote a Behat test for the second formatter
* TODO - write kernel test for the first formatter when RDF entity works with Drupal 8.6
- Added: 2 formatters
- Added: Behat test for the second formatter
```sh
```
=> OPENEUROPA-1191: OE Content field formatters

modules/oe_content_announcement/config/install/field.storage.rdf_entity.oe_announcement_body.yml, modules/oe_content_announcement/config/install/field.storage.rdf_entity.oe_announcement_description.yml, modules/oe_content_announcement/config/install/field.storage.rdf_entity.oe_announcement_introduction.yml, modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_description.yml, modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_tasks_description.yml, modules/oe_content_event/config/install/field.storage.rdf_entity.oe_event_description.yml, modules/oe_content_event/config/install/field.storage.rdf_entity.oe_event_introduction.yml
Added field mappings for the fields which use text formats.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1200: Map text format in oe_content on all fields which use it

composer.json, runner.yml.dist
The PR https://github.com/ec-europa/rdf_entity/pull/65 has been merged so we can remove the patch.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1199: Removing the patch for RDF working with Drupal 8.6.

oe_content.services.yml, src/Event/DepartmentReferencingEvent.php, src/EventSubscriber/DefaultDepartmentReferencingSubscriber.php, src/Plugin/Field/FieldFormatter/RdfEntityReferenceDepartmentUrlFormatter.php
In order to allow others to provide a way to map a department rdf entity to a department term, we refactored the formatter to dispatch an event. This case was made apparent by the use of the content broker in the demo site which altered the query and disallowed departments from being queryable on certain sites.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1188: Refactoring the department referencing to a dispatcher.

oe_content.module
This is some left over code from when the RDF taxonomy was used. Since we moved to RDF SKOS, this is no longer needed. And it breaks stuff.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1384: Removing legacy code from when RDF Taxonomy was used.

README.md, behat.yml.dist, composer.json
After moving from drupal-extension v3 to v4 Drupal\MinkExtension has to be used.
=> OPENEUROPA-1609 Fix behat.yml.dist to use drupal-extension properly.

modules/oe_content_news/config/install/node.type.oe_news.yml, modules/oe_content_page/config/install/node.type.oe_page.yml
Remove preview mode from content types.
- Added:
- Changed:
- Deprecated:
- Removed: Preview mode from content types
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1679: Remove preview mode from content types.

composer.json, modules/oe_content_news/config/install/field.field.node.oe_news.oe_news_author.yml, modules/oe_content_news/config/install/field.field.node.oe_news.oe_news_subject.yml, modules/oe_content_page/config/install/field.field.node.oe_page.oe_page_author.yml, modules/oe_content_page/config/install/field.field.node.oe_page.oe_page_subject.yml, oe_content.module, src/PublicationsOfficeSkosGraphSetup.php
Exported the config for the Concept reference fields. See https://github.com/openeuropa/rdf_skos/pull/10 for why.
=> OPENEUROPA-1690: Adding Skos Concept reference field config.

modules/oe_content_news/config/install/field.field.node.oe_news.oe_news_publication_date.yml, tests/features/news.feature
Remove the default value on the publication date field and remove the required condition so it uses the current date.
- Added:
- Changed:
- Deprecated:
- Removed: Default value from publication date.
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1730: Remove default value on publication field.

.drone.yml, modules/oe_content_news/config/install/field.field.node.oe_news.oe_news_subject.yml, modules/oe_content_page/config/install/field.field.node.oe_page.oe_page_subject.yml, src/PublicationsOfficeSkosGraphSetup.php
Replace eurovoc on oe_content fields.
- Added:
- Changed: Replace eurovoc on oe_content fields.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1709: Replace eurovoc with digital europa thesaurus.

modules/oe_content_news/config/install/core.entity_form_display.node.oe_news.default.yml, modules/oe_content_news/config/install/field.field.node.oe_news.oe_news_publication_date.yml, modules/oe_content_news/config/install/field.storage.node.oe_news_publication_date.yml, modules/oe_content_news/oe_content_news.info.yml, tests/Behat/FeatureContext.php, tests/features/news.feature
Make publication date field a datetime field.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1724: Make publication date a datetime field.

modules/oe_content_news/config/optional/language.content_settings.node.oe_news.yml, modules/oe_content_page/config/optional/language.content_settings.node.oe_page.yml
Similar to how [OE Paragraphs](https://github.com/openeuropa/oe_paragraphs/blob/master/config/optional/language.content_settings.paragraph.oe_list_item.yml) provides language settings for the paragraph types, we need to provide our own for the content types.
=> OPENEUROPA-1852: Default and optional content language settings for the content types.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1864: Update Changelog for release 1.0.0-beta1.

modules/oe_content_page/oe_content_page.info.yml, modules/oe_content_persistent/oe_content_persistent.info.yml, oe_content.info.yml
Add missing config_devel entries
- Added: Add missing config_devel entries
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1856: Add missing config_devel entries.

composer.json, modules/oe_content_persistent/tests/src/Functional/PersistentUrlControllerTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2259: Fix behat/mink-selenium2-driver missing branch.

oe_content.post_update.php, src/PublicationsOfficeSkosGraphSetup.php
Create the country corporate vocabulary in rdf skos. 
Ensure it gets added to the remote triple store self-update thing.
See attachment for the values.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2224: Add support of Country corporate vocabulary.

modules/oe_content_persistent/src/Plugin/Filter/FilterPurl.php, modules/oe_content_persistent/tests/src/Kernel/PersistentUrlFilterTest.php
The persistent url keeps the purl target as it is if it doesn't find the target uuid entity. If no entity is found we revert to a 404 page.
- Added:
- Changed: The persistent url keeps the purl target as it is if it doesn't find the target uuid entity. If no entity is found we revert to a 404 page.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2318: Resort to 404 pages if no entity is found for a uuid on the persistent text filter.

modules/oe_content_timeline_field/oe_content_timeline_field.module, modules/oe_content_timeline_field/src/TmgmtTimelineFieldProcessor.php
When testing this:
* Install the component and make sure stuff doesn't break with the TMGMT module missing.
* Install it in EWCMS where we have local translation and ensure that translating a timeline field, the title doesn't get HTML tags in.
=> OPENEUROPA-2488: TMGMT field preprocessor for the Timeline field.

modules/oe_content_publication/config/install/field.field.node.oe_publication.oe_publication_date.yml
No upgrade path needed here because we don't want to force users of the component to automatically change their field config. They have the option to run their own upgrade path if they want.
=> OPENEUROPA-2487: Publication date field should not be translatable.

modules/oe_content_persistent/src/Plugin/Filter/FilterPurl.php, modules/oe_content_persistent/tests/src/Kernel/PersistentUrlFilterTest.php
In the persistent url logic we rebuild urls without anchors. Rob contributed a PR to take care of this problem. We should complete the solution with doing the same with query parameters.
https://github.com/openeuropa/oe_content/pull/136
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2584: Keep query parameters and fragments from PURL.

modules/oe_content_page/config/install/field.field.node.oe_page.oe_subject.yml
Set subject field optional for Page content type.
- Added:
- Changed: required status of subject field in Page
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2801: Set subject field optional for Page content type.

behat.yml.dist, modules/oe_content_entity/modules/oe_content_entity_contact/config/install/core.entity_form_display.oe_contact.oe_general.default.yml, modules/oe_content_entity/modules/oe_content_entity_contact/config/install/core.entity_form_display.oe_contact.oe_press.default.yml, modules/oe_content_entity/modules/oe_content_entity_contact/config/install/core.entity_view_display.oe_contact.oe_general.default.yml, modules/oe_content_entity/modules/oe_content_entity_contact/config/install/core.entity_view_display.oe_contact.oe_press.default.yml, modules/oe_content_entity/modules/oe_content_entity_contact/config/install/field.field.oe_contact.oe_general.oe_social_media.yml, modules/oe_content_entity/modules/oe_content_entity_contact/config/install/field.field.oe_contact.oe_press.oe_social_media.yml, modules/oe_content_entity/modules/oe_content_entity_contact/config/install/field.storage.oe_contact.oe_social_media.yml, modules/oe_content_entity/modules/oe_content_entity_contact/oe_content_entity_contact.info.yml, tests/Behat/Content/Contact/GeneralContactContext.php, tests/Behat/Content/Contact/PressContactContext.php, tests/features/event.feature
Add social media links field to Press and General bundles.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2771: Add social media links field to Press and General bundles.

CHANGELOG.md
Update CHANGELOG.md for release 1.8.1.
- Added:
- Changed: Update CHANGELOG.md for release 1.8.1.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-3185: Prepare release 1.8.1.

composer.json, modules/oe_content_event/README.md, modules/oe_content_event/config/install/field.field.node.oe_event.oe_event_contact.yml, modules/oe_content_event/config/install/field.field.node.oe_event.oe_event_venue.yml, modules/oe_content_event/oe_content_event.info.yml, modules/oe_content_event/oe_content_event.post_update.php, modules/oe_content_event/tests/src/Kernel/EventKernelTestBase.php
Add composite_reference module and configure event to use it.
- Added: Composite reference module.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-3135: Add composite_reference module and configure event to use it.

composer.json, modules/oe_content_event/README.md
Use alpha1 release for composite_reference.
- Added:
- Changed: Use alpha1 release for composite_reference.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-3135: Use alpha1 release for composite_reference.

modules/oe_content_entity/modules/oe_content_entity_contact/oe_content_entity_contact.module, modules/oe_content_entity/modules/oe_content_entity_organisation/oe_content_entity_organisation.module, modules/oe_content_entity/modules/oe_content_entity_venue/oe_content_entity_venue.module, modules/oe_content_entity/oe_content_entity.module, modules/oe_content_entity/src/Entity/CorporateEntityInterface.php
Change log
Added:
* Constants PUBLISHED, NOT_PUBLISHED to CorporateEntityInterface.
Changed:
* Corporate entities use template oe_content_entity as a base.
=> OPENEUROPA-3380: Use base hook for templates of corporate entities.

modules/oe_content_persistent/config/install/oe_content_persistent.settings.yml, modules/oe_content_persistent/config/schema/oe_content_persistent.schema.yml, modules/oe_content_persistent/oe_content_persistent.post_update.php, modules/oe_content_persistent/oe_content_persistent.services.yml, modules/oe_content_persistent/src/ContentUrlResolver.php, modules/oe_content_persistent/src/ContentUrlResolverInterface.php, modules/oe_content_persistent/src/ContentUuidResolver.php, modules/oe_content_persistent/src/Controller/PersistentUrlController.php, modules/oe_content_persistent/src/Event/PersistentUrlResolverEvent.php, modules/oe_content_persistent/src/Form/PurlSettingsForm.php, modules/oe_content_persistent/src/Plugin/Filter/FilterPurl.php, modules/oe_content_persistent/tests/modules/oe_content_persistent_test/oe_content_persistent_test.services.yml, modules/oe_content_persistent/tests/modules/oe_content_persistent_test/src/EventSubscriber/PersistentUrlResolverSubscriber.php, modules/oe_content_persistent/tests/src/Functional/PersistentUrlControllerTest.php, modules/oe_content_persistent/tests/src/Functional/PurlSettingsTest.php, modules/oe_content_persistent/tests/src/Kernel/PersistentUrlFilterTest.php, modules/oe_content_persistent/tests/src/Kernel/PersistentUrlTest.php
Refactor the PURL module to allow for other entity types
- Added: Event to resolve URLs.
- Changed: Moved supported entity types to configuration.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-94: Refactor the PURL module to allow for other entity types

composer.json, modules/oe_content_event/README.md
Fix inline entity edit form duplicate form.
- Added: patch fixed_duplicate_rows-3162384-16.patch
=> EWPP-196: Fix inline entity edit form duplicate form

behat.yml.dist, modules/oe_content_event/config/install/core.entity_form_display.node.oe_event.default.yml, modules/oe_content_event/config/install/core.entity_view_display.node.oe_event.default.yml, modules/oe_content_event/config/install/field.field.node.oe_event.body.yml, modules/oe_content_event/config/install/field.field.node.oe_event.oe_event_contact.yml, modules/oe_content_event/config/install/field.field.node.oe_event.oe_event_venue.yml, modules/oe_content_event/oe_content_event.info.yml, modules/oe_content_event/oe_content_event.module, modules/oe_content_event/oe_content_event.post_update.php, modules/oe_content_event/src/Plugin/Validation/Constraint/EventFieldsRequiredValidator.php, src/Utility/ContentFormUtilities.php, tests/features/event.feature
Event ; make 'Venue' and 'Organiser' fields optional.
- Changed:
- Venue field is not mandatory
- widget "Inline entity form - Complex" is now used
- Organiser field is not mandatory
- removed useless Validation
- Behat tests about required fieds
=> EWPP-125: Make 'Venue' and 'Organiser' fields optional.

composer.json
Patch https://www.drupal.org/project/entity_browser/issues/2851580#comment-13667638 for entity browser resolves the issue.
This ticket has to be tested in EWCMS.
=> EWPP-313: Media entity reference is replaced with content owner after removing media.

translations/oe_content-cs.po, translations/oe_content-da.po, translations/oe_content-de.po, translations/oe_content-el.po, translations/oe_content-es.po, translations/oe_content-et.po, translations/oe_content-fi.po, translations/oe_content-fr.po, translations/oe_content-ga.po, translations/oe_content-hr.po, translations/oe_content-hu.po, translations/oe_content-it.po, translations/oe_content-lt.po, translations/oe_content-lv.po, translations/oe_content-mt.po, translations/oe_content-nl.po, translations/oe_content-pl.po, translations/oe_content-pt-pt.po, translations/oe_content-ro.po, translations/oe_content-sk.po, translations/oe_content-sl.po, translations/oe_content-sv.po
Remove non necessary context from translations.
- Added:
- Changed: Remove non necessary context from translations.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-371: Remove non necessary context from translations.

translations/oe_content-sk.po, translations/oe_content-sl.po
Lowercase month names in slovakian and slovenian.
- Added:
- Changed: Lowercase month names in slovakian and slovenian.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-371: Lowercase month names in slovakian and slovenian.

composer.json
Use up to date patch for field_group.
- Added:
- Changed: Use up to date patch for field_group.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-406: Use up to date patch for field_group.

composer.json, modules/oe_content_event/README.md, modules/oe_content_news/README.md, modules/oe_content_organisation/README.md, modules/oe_content_persistent/src/Plugin/Linkit/Matcher/MediaPurlMatcher.php, modules/oe_content_project/README.md
This PR cherry-picks that specific commit from another branch, so that it can be released as a patch release in 1.11.1. The branch release-1.11.x has been branched off the 1.11.0 tag.
=> EWPP-443: Fixing Media PURL matcher dependency calculation.

README.md, composer.json, oe_content.module, tests/FunctionalJavascript/DefaultContentOwnerTest.php
Set the site-wide Content Owner value(s) as default value(s) in the new content node forms.
- Added: new hook_ENTITY_TYPE_prepare_form() and a functional test
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
=> EWPP-615: Set default content owner values when creating new content
