- modules/oe_content_announcement/config/install/rdf_entity.mapping.rdf_entity.oe_announcement.yml
- modules/oe_content_event/config/install/rdf_entity.mapping.rdf_entity.oe_event.yml
RDF mapping for base fields:
* author (uid)
* changed
* created
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1144: Map the created date, changed date and author fields of all content types

- README.md
- modules/oe_content_department/config/install/core.entity_form_display.rdf_entity.oe_department.default.yml
- modules/oe_content_department/config/install/core.entity_view_display.rdf_entity.oe_department.default.yml
- modules/oe_content_department/config/install/field.field.rdf_entity.oe_department.oe_department_description.yml
- modules/oe_content_department/config/install/field.field.rdf_entity.oe_department.oe_department_links.yml
- modules/oe_content_department/config/install/field.field.rdf_entity.oe_department.oe_department_name.yml
- modules/oe_content_department/config/install/field.field.rdf_entity.oe_department.oe_department_subject.yml
- modules/oe_content_department/config/install/field.field.rdf_entity.oe_department.oe_department_tasks_description.yml
- modules/oe_content_department/config/install/field.field.rdf_entity.oe_department.oe_department_type.yml
- modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_description.yml
- modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_links.yml
- modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_name.yml
- modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_subject.yml
- modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_tasks_description.yml
- modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_type.yml
- modules/oe_content_department/config/install/rdf_entity.mapping.rdf_entity.oe_department.yml
- modules/oe_content_department/config/install/rdf_entity.rdfentity.oe_department.yml
- modules/oe_content_department/oe_content_department.info.yml
- modules/oe_content_department/oe_content_department.module
- oe_content.module
- runner.yml.dist
- tests/features/department.feature
* Department bundle on RDF entity type
* Reference fields to existing vocabularies
* Title of the department is "hidden" and gets added on presave from the vocabulary reference
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1104: Department content type

- modules/oe_content_announcement/config/install/core.entity_form_display.rdf_entity.oe_announcement.default.yml
- modules/oe_content_department/config/install/core.entity_form_display.rdf_entity.oe_department.default.yml
- modules/oe_content_event/config/install/core.entity_form_display.rdf_entity.oe_event.default.yml
Using vertical tabs.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1102: Using vertical tabs on all the bundles.

- modules/oe_content_announcement/config/install/field.storage.rdf_entity.oe_announcement_subject.yml
- modules/oe_content_department/config/install/field.storage.rdf_entity.oe_department_subject.yml
- modules/oe_content_event/config/install/field.storage.rdf_entity.oe_event_subject.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1203: Make the eurovoc reference fields in oe_content multivalue (unlimited)

- composer.json
Using the openeuropa namespaced rdf_skos
- Update composer.json
> OPENEUROPA-1384: Using the openeuropa namespaced rdf_skos.

- composer.json
The correct package name is fixed.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1422: Fixing easyrdf package version.

- README.md
- composer.json
- runner.yml.dist
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1498: Add documentation on OE Content on how to use this component on a site

- behat.yml.dist
- composer.json
- tests/features/announcement.feature
- tests/features/department.feature
- tests/features/event.feature
> OPENEUROPA-1522: Make sure we don't use Drupal paths in Behat scenarios.

- .drone.yml
> OPENEUROPA-1533: Add --strict flag for Behat tests execution.

- composer.json
- runner.yml.dist
Added the SKOS vocabs + locking RDF entity version.
> OPENEUROPA-1604: Adding new SKOS vocabularies.

- oe_content.tokens.inc
- tests/Kernel/ShortTitleTokenReplaceTest.php
Added short title token and associated kernel tests.
> OPENEUROPA-1723: Short title token

- modules/oe_content_news/config/install/core.entity_view_display.node.oe_news.default.yml
- modules/oe_content_news/oe_content_news.install
- tests/features/news.feature
> OPENEUROPA-1659: Updating the News view display.

- modules/oe_content_news/config/install/core.entity_view_display.node.oe_news.teaser.yml
- modules/oe_content_news/oe_content_news.info.yml
> OPENEUROPA-1672: Enable and configure the teaser view mode for news.

- composer.json
> OPENEUROPA-1821: Updating dependencies.

- CHANGELOG.md
> OPENEUROPA-1766: Preparing release 0.4.2.

- .drone.yml
- phpunit.xml.dist
Removed drone permission fix
- Added:
- Changed: Removed drone permission fix
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1897: Removed drone permission fix.

- composer.json
- docker-compose.yml
- modules/oe_content_policy/config/install/field.field.node.oe_policy.oe_author.yml
- runner.yml.dist
- tests/features/policy.feature
Correction of field label
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1927: Update Author field label.

- CHANGELOG.md
- README.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> RELEASE-1.0.0: Update change log for release 1.0.0.

- modules/oe_content_timeline_field/README.md
- modules/oe_content_timeline_field/config/schema/oe_content_timeline_field.schema.yml
- modules/oe_content_timeline_field/oe_content_timeline_field.info.yml
- modules/oe_content_timeline_field/oe_content_timeline_field.module
- modules/oe_content_timeline_field/src/Plugin/Field/FieldFormatter/TimelineFieldFormatter.php
- modules/oe_content_timeline_field/src/Plugin/Field/FieldType/TimelineFieldItem.php
- modules/oe_content_timeline_field/src/Plugin/Field/FieldWidget/TimelineFieldWidget.php
- modules/oe_content_timeline_field/templates/timeline.html.twig
- modules/oe_content_timeline_field/tests/Kernel/TimelineFieldTest.php
- runner.yml.dist
Added timeline field type definition with widget+formatter and a default twig template.
> OPENEUROPA-2047: Create timeline field type definition.

- modules/oe_content_persistent/src/Controller/PersistentUrlController.php
- modules/oe_content_persistent/src/EventSubscriber/PersistentUrlRedirectSubscriber.php
- modules/oe_content_persistent/tests/src/Functional/PersistentUrlControllerTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-2282: [oe_content] Caching issue on persistent urls.

- .drone.yml
- docker-compose.yml
- modules/oe_content_news/config/install/field.field.node.oe_news.oe_subject.yml
- modules/oe_content_page/config/install/field.field.node.oe_page.oe_subject.yml
- modules/oe_content_policy/config/install/field.field.node.oe_policy.oe_subject.yml
- modules/oe_content_publication/config/install/field.field.node.oe_publication.oe_subject.yml
- oe_content.post_update.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-2101: Update selected skos concept in subject field.

- modules/oe_content_event/config/install/core.entity_form_display.event_profile.oe_event_partner.default.yml
- modules/oe_content_event/config/install/core.entity_view_display.event_profile.oe_event_partner.default.yml
- modules/oe_content_event/config/install/field.field.event_profile.oe_event_partner.image.yml
- modules/oe_content_event/config/install/field.field.event_profile.oe_event_partner.website.yml
- modules/oe_content_event/config/install/field.storage.event_profile.image.yml
- modules/oe_content_event/config/install/field.storage.event_profile.website.yml
- modules/oe_content_event/config/install/oe_content_event.event_profile_type.oe_event_partner.yml
- modules/oe_content_event/config/optional/language.content_settings.event_profile.oe_event_partner.yml
Behat tests will be introduced in the ticket where we add the inline entity form reference to event content type. **Important**: https://github.com/openeuropa/oe_content/pull/117 to be merged at first!
> OPENEUROPA-2206: Create Event partner bundle.

- modules/oe_content_event/config/install/core.entity_form_display.event_profile.oe_event_contact.default.yml
- modules/oe_content_event/config/install/core.entity_view_display.event_profile.oe_event_contact.default.yml
- modules/oe_content_event/config/install/field.field.event_profile.oe_event_contact.address.yml
- modules/oe_content_event/config/install/field.field.event_profile.oe_event_contact.contact_type.yml
- modules/oe_content_event/config/install/field.field.event_profile.oe_event_contact.email.yml
- modules/oe_content_event/config/install/field.storage.event_profile.address.yml
- modules/oe_content_event/config/install/field.storage.event_profile.contact_type.yml
- modules/oe_content_event/config/install/field.storage.event_profile.email.yml
- modules/oe_content_event/config/install/oe_content_event.event_profile_type.oe_event_contact.yml
- modules/oe_content_event/config/optional/language.content_settings.event_profile.oe_event_contact.yml
- modules/oe_content_event/config/optional/language.content_settings.node.oe_event.yml
- modules/oe_content_event/tests/Kernel/EventProfileTest.php
Behat tests will be introduced in the ticket where we add the inline entity form reference to event content type. Important: #117 and #118 to be merged at first!
> OPENEUROPA-2207: Create Event contact bundle.

- behat.yml.dist
- modules/oe_content_event/config/install/core.entity_form_display.event_profile.oe_event_contact.default.yml
- modules/oe_content_event/config/install/core.entity_form_display.node.oe_event.default.yml
- modules/oe_content_event/config/install/core.entity_view_display.node.oe_event.default.yml
- modules/oe_content_event/config/install/field.field.node.oe_event.oe_event_contact.yml
- modules/oe_content_event/config/install/field.storage.node.oe_event_contact.yml
- tests/Behat/FeatureContext.php
- tests/features/event.feature
https://github.com/openeuropa/oe_content/pull/121 to be merged at first!
> OPENEUROPA-2213: Add event contact reference to event.

- behat.yml.dist
- composer.json
- modules/oe_content_event/config/install/core.entity_form_display.node.oe_event.default.yml
- modules/oe_content_event/config/install/field.storage.node.oe_event_type.yml
- tests/features/event.feature
Reoganize fields and field groups according to requirements.
- Added:
- Changed: Reoganize fields and field groups according to requirements
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-2428: Reoganize fields and field groups according to requirements

- behat.yml.dist
- modules/oe_content_event/config/install/field.field.node.oe_event.oe_event_status.yml
- modules/oe_content_event/oe_content_event.module
- tests/Behat/FeatureContext.php
- tests/Traits/UtilityTrait.php
- tests/features/event.feature
Branched out of https://github.com/openeuropa/oe_content/pull/138
> OPENEUROPA-2532: Set default value for event status.

- translations/oe_content-hr.po
- translations/oe_content-lv.po
- translations/oe_content-mt.po
Add translations for hr, lv and mt.
> OPENEUROPA-2534: Add translations for hr and mt.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Update CHANGELOG.md for release 1.6.0.

- composer.json
- tests/features/event.feature
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-0000: Update version of inline_entity_form.

- modules/oe_content_event/config/install/core.entity_form_display.node.oe_event.default.yml
- tests/Behat/DateFieldContext.php
- tests/features/event.feature
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-2805: [Event] Date field widgets.

- modules/oe_content_event/config/install/core.base_field_override.node.oe_event.title.yml
- modules/oe_content_event/config/install/core.entity_form_display.node.oe_event.default.yml
- modules/oe_content_event/config/install/field.field.node.oe_event.oe_subject.yml
- modules/oe_content_event/config/install/field.field.node.oe_event.oe_teaser.yml
- tests/features/content-types.feature
- tests/features/event.feature
- tests/features/news.feature
- tests/features/page.feature
- tests/features/policy.feature
- tests/features/publication.feature
https://github.com/openeuropa/oe_content/pull/165 needs to be merged first!
> OPENEUROPA-2981: [Event] Adapt common fields.

- README.md
- composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-2943: Update composer.json.

- composer.json
- oe_content.services.yml
- src/PublicationsOfficeSkosGraphSetup.php
Use new proposed rdf skos service, see https://github.com/openeuropa/rdf_skos/pull/46
- Deprecated: PublicationsOfficeSkosGraphSetup
> OPENEUROPA-3044: Deprecate PublicationsOfficeSkosGraphSetup

- composer.json
- modules/oe_content_event/config/install/core.entity_form_display.node.oe_event.default.yml
- oe_content.services.yml
- src/PublicationsOfficeSkosGraphSetup.php
- tests/features/event.feature
Merge 'master' into 'EPIC-Project'
- Added: 
- [Merge pull request #190 from openeuropa/OPENEUROPA-3058](https://github.com/openeuropa/oe_content/commit/01bf28c22edf2817ac3cada7f9e9411557ab422e)
- [Merge pull request #198 from openeuropa/OPENEUROPA-3044](https://github.com/openeuropa/oe_content/commit/318f737bb6c4dfab00d5ec4a24688ef7024972cc)
> Merge 'master' into 'EPIC-Project'

- tests/Behat/Content/CorporateContentContext.php
- tests/Behat/Context/Annotation/EntityAwareAnnotationReader.php
- tests/Behat/Hook/Call/AfterSaveEntity.php
- tests/Behat/Hook/Scope/AfterSaveEntityScope.php
- tests/Behat/Hook/Scope/SaveEntityScopeBase.php
This PR isolated only one commit from #187 that adds a new Behat hook. I'd need this in master to unblock work on another PR before OPENEUROPA-3050 gets in.
> OPENEUROPA-3050: Add after entity save behat hook.

- .drone.yml
- docker-compose.yml
- modules/oe_content_project/config/install/core.entity_form_display.node.oe_project.default.yml
- modules/oe_content_project/config/install/core.entity_view_display.node.oe_project.default.yml
- modules/oe_content_project/config/install/field.field.node.oe_project.oe_project_funding_programme.yml
- modules/oe_content_project/config/install/field.storage.node.oe_project_funding_programme.yml
- modules/oe_content_project/oe_content_project.info.yml
- modules/oe_content_project/oe_content_project.install
- src/PublicationsOfficeSkosGraphSetup.php
- tests/features/project.feature
Add "Funding Programme" field
- Added: Funding programme skos reference field
```sh
```
> OPENEUROPA-2624: Add "Funding programme" field

- composer.json
Removing the patches from typed_link that have been merged and released.
> OPENEUROPA-0001: Removing typed_link patches.

- CHANGELOG.md
Prepare 1.9.0 release.
- Added:
- Changed: Update changelog for 1.9.0 release.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare 1.9.0 release.

- behat.yml.dist
- composer.json
- modules/oe_content_project/config/install/core.entity_form_display.node.oe_project.default.yml
- modules/oe_content_project/config/install/core.entity_view_display.node.oe_project.default.yml
- modules/oe_content_project/config/install/field.field.node.oe_project.oe_project_featured_media.yml
- modules/oe_content_project/config/install/field.storage.node.oe_project_featured_media.yml
- modules/oe_content_project/oe_content_project.info.yml
- tests/Behat/Content/Node/ProjectContentContext.php
- tests/features/project.feature
Add featured media field to project content type.
- Added: `oe_project_featured_media` field
- Fixed: Export config with `/admin/config/development/configuration/single/export` so lot of out of scope changes.
> EWPP-32: Add featured media field to project content type.

- composer.json
- modules/oe_content_event/README.md
- modules/oe_content_project/README.md
Possible solution of absent title is provided. See issue page https://www.drupal.org/project/inline_entity_form/issues/2842744.
> EWPP-28: Improve inline entity form complex to display title on create form.

- modules/oe_content_reference_code_field/README.md
- modules/oe_content_reference_code_field/config/install/field.storage.node.oe_reference_code.yml
- modules/oe_content_reference_code_field/oe_content_reference_code_field.info.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Epic tender update 20200818

- modules/oe_content_entity/modules/oe_content_entity_contact/oe_content_entity_contact.module
- modules/oe_content_entity/modules/oe_content_entity_organisation/oe_content_entity_organisation.module
- modules/oe_content_entity/modules/oe_content_entity_venue/oe_content_entity_venue.module
- modules/oe_content_entity/oe_content_entity.module
Corporate entities use default preprocess that is invoked by template_preprocess_HOOK().
See
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-3119?focusedCommentId=4186907&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4186907 
and 
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-3380?focusedCommentId=4160133&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4160133
> OPENEUROPA-3119: Use default preprocess for corporate entities.

- modules/oe_content_redirect_link_field/README.md
- modules/oe_content_redirect_link_field/config/install/field.storage.node.oe_redirect_link.yml
- modules/oe_content_redirect_link_field/oe_content_redirect_link_field.info.yml
- modules/oe_content_redirect_link_field/oe_content_redirect_link_field.module
- modules/oe_content_redirect_link_field/tests/src/FunctionalJavascript/NodeFormRedirectLinkTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-118: Create redirect link field.

- behat.yml.dist
- modules/oe_content_project/config/install/core.entity_form_display.node.oe_project.default.yml
- modules/oe_content_project/config/install/core.entity_view_display.node.oe_project.default.yml
- modules/oe_content_project/config/install/field.field.node.oe_project.oe_project_locations.yml
- modules/oe_content_project/config/install/field.storage.node.oe_project_locations.yml
- modules/oe_content_project/oe_content_project.info.yml
- tests/features/project.feature
"Project locations" (machine name 'oe_project_locations') field has been added to Project node.
> OPENEUROPA-2622: Add 'Location' field type and add 'Project locations' field to Project content type.	

- modules/oe_content_redirect_link_field/oe_content_redirect_link_field.services.yml
- modules/oe_content_redirect_link_field/src/EventSubscriber/RedirectSubscriber.php
- modules/oe_content_redirect_link_field/src/PathProcessor/PathProcessorRedirectLink.php
- modules/oe_content_redirect_link_field/tests/src/Functional/RedirectSubscriberTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-121: Redirect event subscriber.

- composer.json
- modules/oe_content_entity/modules/oe_content_entity_contact/README.md
- modules/oe_content_event/README.md
- modules/oe_content_social_media_links_field/README.md
- modules/oe_content_social_media_links_field/oe_content_social_media_links_field.info.yml
- oe_content.info.yml
Rebase redirect link epic.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-117: Redirect link rebase

- modules/oe_content_tender/src/TenderNodeWrapper.php
- modules/oe_content_tender/src/TenderNodeWrapperInterface.php
- modules/oe_content_tender/tests/src/Kernel/TenderKernelTestBase.php
- modules/oe_content_tender/tests/src/Kernel/TenderNodeWrapperTest.php
TenderNodeWrapper has been added.
> EWPP-63: Theme "Call for tender" full view

- modules/oe_content_call_tenders/config/install/core.base_field_override.node.oe_call_tenders.title.yml
- tests/Behat/Content/Node/CallForTendersContentContext.php
- tests/Behat/Content/Node/TenderContentContext.php
- tests/Behat/DateFieldContext.php
- tests/features/call_tenders.feature
Adding new class CallForTendersContentContext.
> EWPP-274: Fix title field name and create behat context for call for tenders.

- modules/oe_content_organisation/README.md
- modules/oe_content_organisation/config/install/field.field.node.oe_organisation.oe_organisation_logo.yml
- modules/oe_content_organisation/oe_content_organisation.info.yml
- tests/features/organisation.feature
Add av portal to logo sources.
- Added: test for av portal value in organisation test
- Changed: logo field settings
> EWPP-323: Add av portal to logo sources.

- modules/oe_content_project/config/install/field.field.node.oe_project.oe_project_locations.yml
- tests/Behat/Content/Contact/GeneralContactContext.php
- tests/Behat/Content/Contact/PressContactContext.php
Update epic branch
- Added:
- Changed: Update epic branch
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-273: Update epic branch.

- composer.json
Add patch to handled multiple value address fields. 
- Added: patch for address module https://www.drupal.org/project/address/issues/2723917#comment-13843160
> EWPP-326: Add patch to for multiple values fields.

- behat.yml.dist
- modules/oe_content_call_proposals/README.md
- modules/oe_content_call_proposals/config/install/field.field.node.oe_call_proposals.body.yml
- modules/oe_content_call_proposals/config/install/field.field.node.oe_call_proposals.oe_call_proposals_journal.yml
- modules/oe_content_persistent/tests/src/Functional/PersistentUrlControllerTest.php
- tests/Behat/Content/Node/CallForProposalsContentContext.php
Update the oe_call_proposals_journal and body instance configuration to not be translatable as convened.
- Changed:
- oe_call_proposals_journal instance config
- body instance condig
> EWPP-436: Fix oe_call_proposals_journal, body instance config.

- README.md
- modules/oe_content_call_tenders/README.md
- modules/oe_content_call_tenders/config/install/core.entity_form_display.node.oe_call_tenders.default.yml
- modules/oe_content_call_tenders/config/post_updates/00001_add_maxlength/core.entity_form_display.node.oe_call_tenders.default.yml
- modules/oe_content_call_tenders/oe_content_call_tenders.post_update.php
- tests/features/call_tenders.feature
Add maxlength to call for tenders.
- Added:
- maxlength for CFT oe_content_short_title, oe_summary, oe_teaser, title
- behat test for new maxlength
> EWPP-517: Add maxlength to call for tenders.

- .gitignore
- modules/oe_content_timeline_field/oe_content_timeline_field.install
- modules/oe_content_timeline_field/oe_content_timeline_field.post_update.php
- modules/oe_content_timeline_field/src/Plugin/Field/FieldType/TimelineFieldItem.php
- modules/oe_content_timeline_field/tests/Kernel/TimelineFieldTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-686: Change timeline "label" column type from "varchar_ascii" to "varchar"
